name: CI/CD
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-inputs:
    runs-on: ubuntu-24.04
    outputs:
      is-default-branch: ${{ steps.set-is-default-branch.outputs.CI_IS_DEFAULT_BRANCH }}

    steps:
      - name: Set is-default-branch
        id: set-is-default-branch
        run: |
          CI_IS_DEFAULT_BRANCH="${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}"
          echo "CI_IS_DEFAULT_BRANCH=${CI_IS_DEFAULT_BRANCH}" >> $GITHUB_OUTPUT
          echo "CI_IS_DEFAULT_BRANCH=${CI_IS_DEFAULT_BRANCH}" >> $GITHUB_ENV
          echo "CI_IS_DEFAULT_BRANCH=${CI_IS_DEFAULT_BRANCH}"

  nix:
    name: Nix
    needs: check-inputs
    uses: ./.github/workflows/nix.yaml
    secrets: inherit

  csharp:
    name: C#
    needs: check-inputs
    uses: ./.github/workflows/csharp.yaml
