name: C#
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_upm:
    name: Build Unity Packages
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Build UPM packages
        run: nix develop -c just all
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: csharp_artifacts
          if-no-files-found: error
          retention-days: 1
          compression-level: 0
          path: |
            build/
