name: C#
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_upm:
    name: Build Unity Packages
    runs-on: ubuntu-24.11
    steps:
      - uses: actions/checkout@v4
      - name: Build UPM packages
        runs: just
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.4.0
        with:
          name: csharp_artifacts
          if-no-files-found: error
          retention-days: 1
          path: |
            build
