name: Nix CI
on:
  workflow_call:
    secrets:
      CACHIX_AUTH_TOKEN:
        required: false

jobs:
  fmt:
    name: Check Nix Formatting
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    # - uses: cachix/cachix-action@v15
    #   with:
    #     name: basis-ci
    #     authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - run: nix develop -c nixpkgs-fmt --check .
